### ISSUE TITLE
isReactImport binding is undefined

### ISSUE THREAD

**Issue by Huulivoide** [danya/react-local#9]
My codebase fails to build with v0.6.x.

On some conditions the `const binding` variable in the isReactImport function is undefined, which leads to the build breaking as the if on the next line references `binding.path`, but binding now being undefined.

Don't have a minimal test case yet. But I can tell from my debugging that such `identifierName`s such as: Promise, console, Array, JSON, document for example lead to this condition.

I don't know how babel works, but adding a check to the if-clause to check that the `binding` is defined before the actual checks, seems to at least provide a functional build.

**Comment by danya** [comment]
Thanks so much for finding the problem! 
It has been fixed in 0b30a94, v0.6.2 includes this fix.
